const OPTIONS = {DSALEVEL: 3, MININGTIMES: 1};
const MAX_HISTORY = 50;
const MINDSALEVEL = 1;
const MAXDSALEVEL = 5;
const MINMININGTIMES = 1;
const MAXMININGTIMES = 5;
const MINNAMELENGTH = 3;
const MAXNAMELENGTH = 15;



